### ISSUE TITLE
Wizualny błąd paska przesuwania na ekranie "Przystanki"

### ISSUE THREAD

**Issue by mtatko** [Wybranowsky/przystanek-mzk#2]
https://user-images.githubusercontent.com/60148744/180616413-00b59234-99ee-41f2-8299-9b5f31aca0aa.mp4

**Comment by wybran** [comment]
👿

**Comment by konhi** [comment]
a u mnie dziala

**Comment by mtatko** [comment]
> a u mnie dziala

Bo w Książu działa wszystko oprócz internetu
